# Generated by Django 5.2.4 on 2025-07-19 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="ai_confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="prescription",
            name="manual_verification_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prescription",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("manual_review", "Manual Review Required"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["user", "-created_at"], name="prescriptio_user_id_626eb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["processing_status"], name="prescriptio_process_95bcc0_idx"
            ),
        ),
    ]
