name: Deploy to Staging

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Configure Docker for GCR
      run: gcloud auth configure-docker ghcr.io
    
    - name: Deploy backend to staging
      run: |
        gcloud run deploy health-guide-backend-staging \
          --image ghcr.io/${{ github.repository_owner }}/health_guide/backend:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --concurrency 80 \
          --max-instances 2 \
          --set-env-vars "SECRET_KEY=${{ secrets.STAGING_SECRET_KEY }}" \
          --set-env-vars "DEBUG=False" \
          --set-env-vars "ENVIRONMENT=staging" \
          --set-env-vars "DATABASE_URL=sqlite:///staging.db" \
          --tag staging
    
    - name: Deploy frontend to staging
      run: |
        gcloud run deploy health-guide-frontend-staging \
          --image ghcr.io/${{ github.repository_owner }}/health_guide/frontend:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --memory 256Mi \
          --cpu 1 \
          --concurrency 80 \
          --max-instances 2 \
          --tag staging
    
    - name: Run smoke tests against staging
      run: |
        sleep 60
        
        BACKEND_URL=$(gcloud run services describe health-guide-backend-staging --platform managed --region us-central1 --format 'value(status.url)')
        FRONTEND_URL=$(gcloud run services describe health-guide-frontend-staging --platform managed --region us-central1 --format 'value(status.url)')
        
        echo "Backend URL: $BACKEND_URL"
        echo "Frontend URL: $FRONTEND_URL"
        
        # Basic health checks
        curl -f "$BACKEND_URL/health/" || exit 1
        curl -f "$FRONTEND_URL/health" || exit 1
        
        echo "✅ Staging deployment successful"
        echo "Backend: $BACKEND_URL"
        echo "Frontend: $FRONTEND_URL"