# Generated by Django 5.2.4 on 2025-07-19 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("call", "Phone Call"),
                            ("email", "Email"),
                            ("push", "Push Notification"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="External service message ID",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="emergencycontact",
            options={"ordering": ["-is_primary", "name"]},
        ),
        migrations.RemoveField(
            model_name="emergencyalert",
            name="is_resolved",
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("general", "General Emergency"),
                    ("medical", "Medical Emergency"),
                    ("fall", "Fall Detection"),
                    ("panic", "Panic Button"),
                    ("medication", "Medication Emergency"),
                    ("test", "Test Alert"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="location_accuracy",
            field=models.FloatField(
                blank=True, help_text="Location accuracy in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="notifications_failed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="notifications_sent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("resolved", "Resolved"),
                    ("cancelled", "Cancelled"),
                    ("test", "Test"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="can_receive_calls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="can_receive_sms",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about this contact"
            ),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("family", "Family Member"),
                    ("friend", "Friend"),
                    ("doctor", "Doctor"),
                    ("caregiver", "Caregiver"),
                    ("neighbor", "Neighbor"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(
                fields=["user", "-created_at"], name="emergency_e_user_id_1f1f67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(
                fields=["user", "status"], name="emergency_e_user_id_09eca6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(
                fields=["alert_type"], name="emergency_e_alert_t_7cdce7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(
                fields=["user", "is_active"], name="emergency_e_user_id_44ecd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(
                fields=["user", "is_primary"], name="emergency_e_user_id_a30ced_idx"
            ),
        ),
        migrations.AddField(
            model_name="emergencynotification",
            name="alert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="emergency.emergencyalert",
            ),
        ),
        migrations.AddField(
            model_name="emergencynotification",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="emergency.emergencycontact",
            ),
        ),
        migrations.AddIndex(
            model_name="emergencynotification",
            index=models.Index(
                fields=["alert", "status"], name="emergency_e_alert_i_515765_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencynotification",
            index=models.Index(
                fields=["contact", "-created_at"], name="emergency_e_contact_514f93_idx"
            ),
        ),
    ]
