# Generated by Django 5.2.4 on 2025-07-18 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("password_reset_request", "Password Reset Request"),
                            ("password_reset_confirm", "Password Reset Confirm"),
                            ("password_change", "Password Change"),
                            ("email_verification", "Email Verification"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("hijack_started", "Hijack Started"),
                            ("hijack_ended", "Hijack Ended"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField()),
                ("details", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="authenticat_user_id_63e710_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="authenticat_action_182ef8_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="authenticat_ip_addr_48e893_idx",
                    ),
                ],
            },
        ),
    ]
