# Generated by Django 5.2.4 on 2025-07-19 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_account_locked_until_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_failed", "Login Failed"),
                    ("password_reset_request", "Password Reset Request"),
                    ("password_reset_confirm", "Password Reset Confirm"),
                    ("password_change", "Password Change"),
                    ("email_verification", "Email Verification"),
                    ("account_locked", "Account Locked"),
                    ("account_unlocked", "Account Unlocked"),
                    ("hijack_started", "Hijack Started"),
                    ("hijack_ended", "Hijack Ended"),
                    ("session_created", "Session Created"),
                    ("session_terminated", "Session Terminated"),
                    ("token_refreshed", "Token Refreshed"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=255, unique=True)),
                ("refresh_token_jti", models.CharField(max_length=255, unique=True)),
                ("device_name", models.CharField(blank=True, max_length=100)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser_name", models.CharField(blank=True, max_length=50)),
                ("browser_version", models.CharField(blank=True, max_length=20)),
                ("os_name", models.CharField(blank=True, max_length=50)),
                ("os_version", models.CharField(blank=True, max_length=20)),
                ("ip_address", models.GenericIPAddressField()),
                ("location", models.CharField(blank=True, max_length=100)),
                ("remember_me", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.AddField(
            model_name="securityauditlog",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.usersession",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "-last_activity"], name="authenticat_user_id_d6a491_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["refresh_token_jti"], name="authenticat_refresh_520b32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_key"], name="authenticat_session_1fea71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["is_active", "-last_activity"],
                name="authenticat_is_acti_2083a0_idx",
            ),
        ),
    ]
